In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("datasets/Question3.csv")
df

,Student,Attendance,PreviousMarks,AssignmentCompletion,QuizScore,Pass
0,Aarav,72,58,65,61,0
1,Sita,91,84,86,88,1
2,Ram,68,52,55,57,0
3,Anisha,94,89,92,91,1
4,Rohan,75,60,62,64,1
5,Priya,88,81,79,85,1
6,Kiran,62,45,48,50,0
7,Nabin,82,69,72,74,1
8,Suman,70,54,58,60,0
9,Alisha,96,93,94,95,1


In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student               20 non-null     str  
 1   Attendance            20 non-null     int64
 2   PreviousMarks         20 non-null     int64
 3   AssignmentCompletion  20 non-null     int64
 4   QuizScore             20 non-null     int64
 5   Pass                  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB


In [4]:
df.isna().sum()

Student                 0
Attendance              0
PreviousMarks           0
AssignmentCompletion    0
QuizScore               0
Pass                    0
dtype: int64

In [5]:
df.columns

Index(['Student', 'Attendance', 'PreviousMarks', 'AssignmentCompletion',
       'QuizScore', 'Pass'],
      dtype='str')

In [6]:
x=df[[
    'Attendance', 'PreviousMarks', 'AssignmentCompletion',
       'QuizScore'
]]


In [7]:
y=df[
    'Pass'
]


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.preprocessing import StandardScaler   
from sklearn.neighbors import KNeighborsClassifier   

In [10]:
x_tro,x_teo,y_tro,y_teo=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [11]:
scaler=StandardScaler()
x_tr=scaler.fit_transform(x_tro)
x_te=scaler.transform(x_teo)

In [12]:
x_tr

array([[ 0.91046547,  0.88513364,  0.89247899,  0.93206825],
       [-0.73704347, -0.72279472, -0.42275321, -0.81859908],
       [ 0.99717646,  1.25619404,  1.0177392 ,  1.12658685],
       [ 0.73704347,  0.57591665,  0.64195857,  0.67271013],
       [ 1.34402045,  1.44172423,  1.39351983,  1.38594497],
       [ 0.39019949,  0.14301286,  0.20354784,  0.28367295],
       [ 0.65033248,  0.69960345,  0.45406826,  0.73754966],
       [-1.17059846, -1.21754191, -1.17431447, -1.20763626],
       [-1.08388746, -1.09385511, -1.04905426, -1.0779572 ],
       [-0.47691048, -0.59910792, -0.61064352, -0.62408048],
       [ 1.08388746,  1.07066384,  1.20562952,  1.06174732],
       [-1.34402045, -1.27938531, -1.6753553 , -1.40215485],
       [ 0.1300665 , -0.04251734,  0.01565753,  0.02431482],
       [ 1.17059846,  1.19435064,  1.26825962,  1.12658685],
       [-0.99717646, -0.78463812, -0.67327363, -0.68892001],
       [-1.60415344, -1.52675891, -1.48746499, -1.53183391]])

In [13]:
model=KNeighborsClassifier(
    n_neighbors=3
)
model.fit(x_tr,y_tro)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",3
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [14]:
prediction=model.predict(x_te)
prediction

array([0, 0, 1, 1])

In [15]:
data1=pd.DataFrame({
    "Acyual":y_teo,
    "Predicted":prediction
})
data1

,Acyual,Predicted
16,0,0
8,0,0
10,1,1
15,1,1


In [16]:
model.predict_proba(x_te)

array([[1.        , 0.        ],
       [1.        , 0.        ],
       [0.33333333, 0.66666667],
       [0.33333333, 0.66666667]])

In [17]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score

In [18]:
print("Accuracy",accuracy_score(y_teo,prediction))
print("Precision",precision_score(y_teo,prediction))
print("F1 score",f1_score(y_teo,prediction))
print("Recall",recall_score(y_teo,prediction))

Accuracy 1.0
Precision 1.0
F1 score 1.0
Recall 1.0


In [19]:
new_data=pd.DataFrame({
    'Attendance':[66],
    'PreviousMarks':[67],
    'AssignmentCompletion':[78],
       'QuizScore':[55]
    
})
new_data

,Attendance,PreviousMarks,AssignmentCompletion,QuizScore
0,66,67,78,55


In [21]:
new_scaled=scaler.transform(new_data)
new_scaled

array([[-1.25730946, -0.16620413,  0.39143816, -1.20763626]])

In [23]:
model.predict(new_scaled)

array([0])

In [22]:
distance,index=model.kneighbors(new_scaled)
print(distance)

[[1.18098572 1.36117871 1.46326118]]


In [24]:
print(index)

[[ 1 14  9]]


In [30]:
print("3 nearest student to new data")
# df.iloc[[1,14,9]] don't check in og data its suffeled by test train so
datatr=pd.DataFrame(
    x_tro, columns=['Attendance', 'PreviousMarks', 'AssignmentCompletion',
       'QuizScore'])


datatr
actual_row_numbers = datatr.index[index[0]]
actual_row_numbers


3 nearest student to new data


Index([0, 14, 4], dtype='int64')

In [31]:
df.iloc[actual_row_numbers]

,Student,Attendance,PreviousMarks,AssignmentCompletion,QuizScore,Pass
0,Aarav,72,58,65,61,0
14,Manish,69,57,61,63,0
4,Rohan,75,60,62,64,1


In [ ]:
distance, index = model.kneighbors(new_scaled)
# kneighbors() returns TWO things: how far each neighbor is (distance),
# and WHERE each neighbor sits in the training data (index/position).
# We need distance to show/verify "closeness", and index to trace back
# to WHO that neighbor actually is (since KNN only stores numbers, not names).

print(index)
# index gives POSITIONS within the training set (not the original df row numbers),
# because kneighbors() has no idea about df's original row labels — it only
# knows "1st row I was trained on, 2nd row, 3rd row..." Since train_test_split
# shuffled the data, position ≠ original df row number anymore.

datatr = pd.DataFrame(x_tro, columns=[...])
# Rebuild the training data as a DataFrame (not numpy) so it keeps its
# ORIGINAL df index attached — this becomes our "translator" between
# position and original identity.

actual_row_numbers = datatr.index[index[0]]
# index[0] = positions from kneighbors (e.g. [1,14,9])
# datatr.index[...] converts each POSITION into its ORIGINAL df row label
# — without this step, we'd have no way to know which real student
# each neighbor actually is.

df.loc[actual_row_numbers]
# Finally, use those real original row numbers to pull the actual student
# rows (with names) from the ORIGINAL df — this answers the real question:
# "which existing students are most similar to this new student?"

In [42]:
data5=pd.DataFrame({
    "name":["A","B"],
    'roll':[4,5]
    
},index=["r","t"])

In [43]:
data5

,name,roll
r,A,4
t,B,5


In [48]:
data5.index[1]

't'