In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('datasets/Question2.csv')
df

,Student,Attendance,MathScore,EnglishScore,QuizScore,MissedClasses,MathSupport,EnglishSupport,AttendanceSupport
0,Aarav,72,55,58,61,1,0,1,0
1,Sita,91,86,84,88,0,0,0,0
2,Ram,68,48,52,55,4,1,1,0
3,Anisha,94,92,89,91,0,0,0,0
4,Rohan,75,60,57,63,2,0,1,0
5,Priya,88,78,81,85,1,0,0,0
6,Kiran,62,42,45,49,5,1,1,1
7,Nabin,82,70,68,72,2,0,0,0
8,Suman,70,50,54,58,3,1,1,0
9,Alisha,96,94,92,95,0,0,0,0


In [6]:
df.isna().sum()

Student              0
Attendance           0
MathScore            0
EnglishScore         0
QuizScore            0
MissedClasses        0
MathSupport          0
EnglishSupport       0
AttendanceSupport    0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student            20 non-null     str  
 1   Attendance         20 non-null     int64
 2   MathScore          20 non-null     int64
 3   EnglishScore       20 non-null     int64
 4   QuizScore          20 non-null     int64
 5   MissedClasses      20 non-null     int64
 6   MathSupport        20 non-null     int64
 7   EnglishSupport     20 non-null     int64
 8   AttendanceSupport  20 non-null     int64
dtypes: int64(8), str(1)
memory usage: 1.5 KB


In [8]:
df.columns

Index(['Student', 'Attendance', 'MathScore', 'EnglishScore', 'QuizScore',
       'MissedClasses', 'MathSupport', 'EnglishSupport', 'AttendanceSupport'],
      dtype='str')

In [12]:
x=df[[ 'Attendance', 'MathScore', 'EnglishScore', 'QuizScore',
       'MissedClasses']]#i think quiz and missed class also required 
x=x.to_numpy()

In [13]:
y=df[['MathSupport', 'EnglishSupport', 'AttendanceSupport']]
y=y.to_numpy()

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [18]:
x_tr

array([[60, 40, 44, 47,  6],
       [65, 45, 48, 51,  5],
       [77, 68, 66, 70,  2],
       [89, 82, 79, 84,  1],
       [92, 88, 90, 87,  0],
       [72, 55, 58, 61,  1],
       [93, 90, 88, 92,  0],
       [75, 60, 57, 63,  2],
       [70, 50, 54, 58,  3],
       [79, 65, 63, 67,  2],
       [88, 78, 81, 85,  1],
       [91, 86, 84, 88,  0],
       [94, 92, 89, 91,  0],
       [69, 56, 59, 60,  3],
       [67, 47, 50, 53,  4],
       [96, 94, 92, 95,  0]])

In [36]:
y_tr
y_te.shape

(4, 3)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
from sklearn.multiclass import OneVsRestClassifier

In [24]:
model=OneVsRestClassifier(LogisticRegression())

In [25]:
model.fit(x_tr,y_tr)

,"estimator estimator: estimator objectA regressor or a classifier that implements :term:`fit`.When a classifier is passed, :term:`decision_function` will be usedin priority and it will fallback to :term:`predict_proba` if it is notavailable.When a regressor is passed, :term:`predict` is used.",LogisticRegression()
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation: the `n_classes`one-vs-rest problems are computed in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: 0.20 `n_jobs` default changed from 1 to None",None
,"verbose verbose: int, default=0The verbosity level, if non zero, progress messages are printed.Below 50, the output is sent to stderr. Otherwise, the output is sentto stdout. The frequency of the messages increases with the verbositylevel, reporting all iterations at 10. See :class:`joblib.Parallel` formore details... versionadded:: 1.1",0
Name,Type,Value
"classes_ classes_: array, shape = [`n_classes`]Class labels.","ndarray[int64](3,)","[0,1,2]"
estimators_ estimators_: list of `n_classes` estimatorsEstimators used for predictions.,list,"[LogisticRegression(), LogisticRegression(), LogisticRegression()]"
label_binarizer_ label_binarizer_: LabelBinarizer objectObject used to transform multiclass labels to binary labels andvice-versa.,LabelBinarizer,LabelBinarize...e_output=True)
multilabel_ multilabel_: booleanWhether a OneVsRestClassifier is a multilabel classifier.,bool,True
n_classes_ n_classes_: intNumber of classes.,int,3
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 0.24,int,5
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'


In [29]:
prediction=model.predict(x_te)

In [30]:
model.predict_proba(x_te)

array([[6.73091116e-07, 2.27770508e-04, 2.68613643e-13],
       [9.99998998e-01, 9.99999998e-01, 9.95919569e-01],
       [9.97724477e-01, 9.99996437e-01, 2.41418772e-02],
       [8.12860615e-09, 4.83220239e-06, 2.06269092e-15]])

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_te, prediction)

1.0

In [55]:
for i, estimator in enumerate(model.estimators_):
    
    print(estimator.coef_)
    print()

[[-0.64727799 -0.16798407 -0.03876213 -0.35645305  0.42860712]]

[[-0.24877341 -0.33502301 -0.35147745 -0.26221705 -0.00143064]]

[[-0.36023231 -0.36026331 -0.36073002 -0.36158178  0.1792586 ]]



In [40]:
actual_df = pd.DataFrame(y_te, columns=['Label1', 'Label2', 'Label3'])
predicted_df = pd.DataFrame(prediction, columns=['Label1', 'Label2', 'Label3'])

print("Actual:")
print(actual_df)
print("Predicted:")
print(predicted_df)


Actual:
   Label1  Label2  Label3
0       0       0       0
1       1       1       1
2       1       1       0
3       0       0       0
Predicted:
   Label1  Label2  Label3
0       0       0       0
1       1       1       1
2       1       1       0
3       0       0       0


In [37]:
prediction.shape

(4, 3)

In [46]:
new_std=pd.DataFrame({
    'Attendance':[55],
    'MathScore':[66],
    'EnglishScore':[56],
    'QuizScore':[67],
    'MissedClasses':[4]
})
new_std=new_std.to_numpy()
new_pre=model.predict(new_std)
data2=pd.DataFrame(new_pre,columns=['MathSupport', 'EnglishSupport', 'AttendanceSupport'])
data2

,MathSupport,EnglishSupport,AttendanceSupport
0,1,1,0


In [52]:
print("Student Support Prediciton:")
print("Math Support:", "YES" if data2.loc[0, 'MathSupport'] == 1 else "NO")
print("English Support:", "YES" if data2.loc[0, 'EnglishSupport'] == 1 else "NO")
print("Attendence Support:", "YES" if data2.loc[0, 'AttendanceSupport'] == 1 else "NO")

Student Support Prediciton:
Math Support: YES
English Support: YES
Attendence Support: NO
